apiVersion: v1
kind: ConfigMap
metadata:
  name: ama-metrics-settings-configmap
  namespace: kube-system
data:
  schema-version: v1
  config-version: ver1
  prometheus-collector-settings: |-
    cluster_alias = ""
    [default-scrape-settings]
      enabled = true
    [default-targets-metrics-keep-list]
      minimalIngestionProfile = false