apiVersion: v1
kind: Service

metadata:
  name: starship-staging-service

  labels:
    app: starship-staging
    env: staging

spec:

  type: LoadBalancer

  selector:
    app: starship-staging

  ports:

  - name: http

    port: 80

    targetPort: 3000
