apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor

metadata:
  name: selector-monitor
  namespace: monitoring
  labels:
    release: dev-monitoring

spec:

  selector:
    matchLabels:
      env : dev

  namespaceSelector:
    matchNames:
      - default

  endpoints:
  - port: http
    path: /metrics
    interval: 15s
