apiVersion: apps/v1
kind: Deployment

metadata:
  name: starship-app-dev

spec:
  replicas: 1

  selector:
    matchLabels:
      app: starship-dev

  template:
    metadata:
      labels:
        app: starship-dev

    spec:
      containers:

      - name: starship

        image: starshipfleetacr.azurecr.io/starship-fleet:latest

        ports:
        - containerPort: 3000
