apiVersion: apps/v1
kind: Deployment
metadata:
  name: starship-fleet
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: starship-fleet
  template:
    metadata:
      labels:
        app: starship-fleet
    spec:
      containers:
        - name: starship-fleet
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: 3000
          livenessProbe:
            httpGet:
              path: /live
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /ready
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
