{{- if .Values.blueGreen.enabled }}
{{- range $slot := list "blue" "green" }}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starship-fleet-{{ $slot }}
  labels:
    app: {{ $.Values.app }}
    slot: {{ $slot }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ $.Values.app }}
      slot: {{ $slot }}
  template:
    metadata:
      labels:
        app: {{ $.Values.app }}
        slot: {{ $slot }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ $.Values.app }}
              slot: {{ $slot }}
        
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ $.Values.app }}
              slot: {{ $slot }}

      containers:
        {{- $ctx := dict "Values" $.Values "slot" $slot }}
        {{- include "starship-fleet.container" $ctx | nindent 8 }}
{{- end }}
{{- else }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: starship-fleet
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app }}
  template:
    metadata:
      labels:
        app: {{ .Values.app }}
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8000"
        prometheus.io/path: "/metrics"
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ .Values.app }}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: ScheduleAnyway
          labelSelector:
            matchLabels:
              app: {{ .Values.app }}
      containers:
        {{- $ctx := dict "Values" .Values "slot" "" }}
        {{- include "starship-fleet.container" $ctx | nindent 8 }}
{{- end }}
