apiVersion: v1
kind: Service
metadata:
  name: starship-fleet-service
spec:
  type: {{ .Values.service.type }}
  selector:
    app: starship-fleet
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
