apiVersion: v1
kind: Service
metadata:
  name: starship-fleet-service
  labels:
    app: {{ .Values.app }}
    env: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}
    {{- if .Values.blueGreen.enabled }}
    slot: {{ .Values.blueGreen.activeSlot }}
    {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
{{- if .Values.blueGreen.enabled }}
{{- $previewSlot := "green" }}
{{- if eq .Values.blueGreen.activeSlot "green" }}
{{- $previewSlot = "blue" }}
{{- end }}
---
apiVersion: v1
kind: Service
metadata:
  name: starship-fleet-preview-service
  labels:
    app: {{ .Values.app }}
    env: {{ .Values.env }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.app }}
    slot: {{ $previewSlot }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8000
{{- end }}
