name: CI/CD - starship-fleet

on:
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    uses: cbnr-devops/GitHub-reusable-workflows/.github/workflows/build.yml@v1
    with:
      image_name: starship-fleet
      image_tag: ${{ github.run_number }}

      install_command: npm ci
      test_command: npm test

      owasp_enabled: true
      owasp_project_name: starship-fleet

      sonar_enabled: true
      sonar_project_key: sk-solar-project_starfleet
      sonar_project_name: starfleet

      trivy_enabled: true

      aws_region: eu-central-1
      aws_account_id: ${{ secrets.AWS_ACCOUNT_ID }}
      ecr_repository: starship-fleet

    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  deploy_dev:
    needs: build
    uses: cbnr-devops/GitHub-reusable-workflows/.github/workflows/deploy.yml@v1
    with:
      environment: dev
      cluster_name: dev-cluster
      aws_region: eu-central-1
      namespace: dev
      helm_path: ./helm/starship-fleet
      release_name: starship-fleet
      image_name: ${{ needs.build.outputs.built_image_name }}
      image_tag: ${{ needs.build.outputs.built_image_tag }}

  deploy_staging:
    if: github.ref_name == 'main'
    needs: deploy_dev
    uses: cbnr-devops/GitHub-reusable-workflows/.github/workflows/deploy.yml@v1
    with:
      environment: staging
      cluster_name: staging-cluster
      aws_region: eu-central-1
      namespace: staging
      helm_path: ./helm/starship-fleet
      release_name: starship-fleet
      image_name: ${{ needs.build.outputs.built_image_name }}
      image_tag: ${{ needs.build.outputs.built_image_tag }}
    environment: staging