name: CI/CD - starship-fleet

on:
  push:
    branches:
      - '*'
  pull_request:
  workflow_dispatch:
    inputs: 
      environment:
        description: 'Environment to deploy to'
        required: true
        default: 'dev'
        type: string
        options:
          - dev
          - staging
          - production

permissions:
  id-token: write
  contents: read

jobs:
  build:
    uses: cbnr-devops/GitHub-reusable-workflows/.github/workflows/build.yml@sks-16
    with:
      image_name: starship-fleet
      image_tag: ${{ github.run_number }}
      install_command: pip install -r requirements.txt
      test_command: npm test

      owasp_enabled: false
      owasp_project_name: starship-fleet

      sonar_enabled: true
      sonar_project_key: sk-solar-project_star-fleet
      sonar_project_name: star-fleet

      trivy_enabled: true

      aws_region: ap-southeast-2           
      aws_account_id: ${{ github.repository_owner == 'cbnr-devops' && '987569578177' || '' }}
      ecr_repository: starship-fleet

    secrets:
      NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      CI_ROLE_ARN:  ${{ secrets.CI_ROLE_ARN }}

  deploy_dev:
    needs: build
    uses: cbnr-devops/GitHub-reusable-workflows/.github/workflows/deploy.yml@sks-16
    with:
      environment: dev
      cluster_name: dev-cluster
      aws_region: ap-southeast-2
      namespace: dev
      helm_path: ./helm/starship-fleet
      values_file: values-dev.yaml
      release_name: starship-fleet
      image_name: 987569578177.dkr.ecr.ap-southeast-2.amazonaws.com/starship-fleet
      image_tag: ${{ github.run_number }}
    secrets:
      CI_ROLE_ARN: ${{ secrets.CI_ROLE_ARN }}

  deploy_staging:
    if: github.ref_name == 'main'
    needs: deploy_dev
    uses: cbnr-devops/GitHub-reusable-workflows/.github/workflows/deploy.yml@sks-16
    with:
      environment: staging
      cluster_name: staging-cluster
      aws_region: ap-southeast-2
      namespace: staging
      helm_path: ./helm/starship-fleet
      values_file: values-dev.yaml
      release_name: starship-fleet
      image_name: 987569578177.dkr.ecr.ap-southeast-2.amazonaws.com/starship-fleet
      image_tag: ${{ github.run_number }}
    secrets:
      CI_ROLE_ARN: ${{ secrets.CI_ROLE_ARN }}