replicaCount: 1

app: starship-fleet

image:
  repository: ""
  tag: latest
  pullPolicy: Always

service:
  type: ClusterIP
  port: 80

blueGreen:
  enabled: false
  activeSlot: blue
  slots:
    blue:
      imageTag: ""
    green:
      imageTag: ""

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi

hpa:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  cpuUtilization: 70
  memoryUtilization: 80